# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

EDITOR='vim'

if [ -f "$HOME/.profile.local" ]; then
    . "$HOME/.profile.local"
fi

# Powerline go first, python second
if [ -x ~/.local/bin/powerline-go ]; then
    export GOPATH=~/.local/
fi
if [ -z "$GOPATH" ] && command powerline-daemon; then
    powerline-daemon -q
fi
