export CLICOLOR=1

if [ -f ~/.zshrc.local ]; then
  . ~/.zshrc.local
fi

POWERLINE_DIR="$(pip show powerline-status 2> /dev/null | fgrep Location | cut -d" " -f2)"
[ -z "$POWERLINE_DIR" ] && POWERLINE_DIR='.local/lib/python2.6/site-packages'
if [ -r $POWERLINE_DIR/powerline/bindings/zsh/powerline.zsh ]; then
	if [ -x $POWERLINE_DIR/bin/powerline ]; then
		POWERLINE_COMMAND=$POWERLINE_DIR/bin/powerline
	fi
	if [ -x $POWERLINE_DIR/EGG-INFO/scripts/powerline-config ]; then
		POWERLINE_CONFIG_COMMAND=$POWERLINE_DIR/EGG-INFO/scripts/powerline-config
	fi
	. $POWERLINE_DIR/powerline/bindings/zsh/powerline.zsh
fi
