Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'preservim/nerdcommenter'
Plug 'dense-analysis/ale'
Plug 'vim-scripts/a.vim', { 'for': ['c', 'h', 'cpp', 'hpp'] }
Plug 'jlanzarotta/bufexplorer'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'mhinz/vim-startify'
Plug 'airblade/vim-rooter'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'hdima/python-syntax' ", { 'for': 'py' }
Plug 'Yggdroot/indentLine'
Plug 'majutsushi/tagbar'
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'michaeljsmith/vim-indent-object'
Plug 'jiangmiao/auto-pairs'
Plug 'easymotion/vim-easymotion'
Plug 'andymass/vim-matchup'
Plug 'ciaranm/detectindent'
Plug 'wincent/terminus'
Plug 'ekalinin/Dockerfile.vim'
Plug 'tmux-plugins/vim-tmux'
Plug 'mhinz/vim-signify'
Plug 'rust-lang/rust.vim'
Plug 'vhda/verilog_systemverilog.vim'
Plug 'farmergreg/vim-lastplace'
Plug 'will133/vim-dirdiff'
Plug 'NLKNguyen/papercolor-theme'
Plug 'reedes/vim-colors-pencil'
Plug 'altercation/vim-colors-solarized'
Plug 'tpope/vim-vividchalk'
Plug 'itchyny/landscape.vim'
Plug 'jonathanfilip/vim-lucius'
Plug 'rakr/vim-one'
Plug 'ryanoasis/vim-devicons'
" Plug 'madox2/vim-ai'
